### ISSUE TITLE
inconsistency referenceing files in current directory

### ISSUE THREAD

**Issue by yomed** [lasso-js/lasso-require#23]
```js
{
    "dependencies": [
        "require: jquery",
        "require: ./file.js",
        "require: file.js",  // does not work
        "./file.js",
        "file.js"
    ]
}
```

`Error: Unable to resolve required module "file.js" `

Is this behavior intentional? Just a bit odd that it is inconsistent across require and non-require.

**Comment by patrick-steele-idem** [comment]
> Is this behavior intentional?

Yes, due to legacy reasons.

> Just a bit odd that it is inconsistent across require and non-require.

Completely agree. We should have always required "./" for relative paths, but it didn't start that way and it would have been a breaking change so we had to stick with allowing relative paths to not begin with "./". We were able to get it correct for "require" dependencies.

I didn't feel this needed to be addressed in the docs, but please let me know if you disagree. Hoping to instead to steer developers to always using "./" for relative paths. In theory, we could have deprecated this in 1.x and removed in 2.x but also probably too late for that :/

I hope that answers your question. Thanks for bringing this up.

**Comment by yomed** [comment]
Haha maybe deprecate in 2.x and remove in 3.x?
